if: type != push OR branch = master OR tag IS present

language: node_js
node_js:
  - '10'
sudo: required

before_install:
  - export NG_CLI_ANALYTICS=ci

script:
  - npm run test:travis
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ./.npmrc

deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on:
    tags: true
